# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2414fdf344d7d97581f267c6fd336ca3a6bf01d45bb7737d1614b880f033ea6e4f9520a0b27a1275a9d4795184b2aca71982c95aec307e6b518b71ec85775cb

test:
  secret_key_base: 15909392c23d2d666ad9e91bc4021cf255fd92fec2f9d29cddf4fdada3b26d0d6a1ceec32a7e3c01845b8d062cab99c70c329f71979f0ded49ed8ea59fc08915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
